name = "BBShiftAutomorphisms"
uuid = "55c8e5b1-f282-4648-a472-8a8fa2cdc5d1"
version = "1.0.0"
authors = ["John Lapeyre"]

[workspace]
projects = ["test", "docs"]

[deps]
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Dictionaries = ">=0.4"
LinearAlgebra = ">=1.10"
Nemo = ">=0.50"
Reexport = ">=1.2"
julia = "1.10"
