"""
    Z6Groups

Provides the `struct` `Z6xZ6`.
"""
module Z6Groups
using Dictionaries: Dictionary, insert!

export generating_set, Z6, Z6xZ6, compute_nr_generators, all_elements_present,
    nr_generators_lookup, check_nr_generators_lookup

"""
    Z6(g::Integer)

Element of the cyclic group Z₆ with coordinate reduced mod 6.

# Examples
```jldoctest
julia> Z6(0) == Z6(6)
true

julia> Z6(1) == Z6(-5)
true
```
"""
struct Z6
    g::Int
    Z6(g::Integer) = new(mod(g, 6))
end

# Choose "multiplication" as the group operation
Base.:*(g::Z6, h::Z6) = Z6(g.g + h.g)
Base.:^(g::Z6, n::Integer) = Z6(n * g.g)
Base.inv(g::Z6) = Z6(6 - g.g)
Base.isless(g::Z6, h::Z6) = isless(g.g, h.g) # For lexicographical sorto

"""
    Z6xZ6

Element of Z₆ × Z₆ with coordinates reduced mod 6.
"""
struct Z6xZ6
    x::Z6
    y::Z6
end

get_x(g::Z6xZ6)::Int = g.x.g
get_y(g::Z6xZ6)::Int = g.y.g

Z6xZ6(x::Integer, y::Integer) = Z6xZ6(Z6(x), Z6(y))
Z6xZ6((x, y)::Tuple{Integer, Integer}) = Z6xZ6(x, y)
Base.:*(g::Z6xZ6, h::Z6xZ6) = Z6xZ6(g.x * h.x, g.y * h.y)
Base.inv(g::Z6xZ6) = Z6xZ6(inv(g.x), inv(g.y))

function Base.isless(g::Z6xZ6, h::Z6xZ6) # For lexicographical sort
    isless(g.x, h.x) && return true
    isless(h.x, g.x) && return false
    return isless(g.y, h.y)
end

Base.show(io::IO, g::Z6xZ6) = print(io, typeof(g), "(", get_x(g), ", ", get_y(g), ")")

"""
    generating_set

A particular generating set for Z6xZ6 that is relatively easy to implement as a circuit.

We include the inverses of each element in this set.

This generating set is definined section in A.2 of "Tour de gross..." near the top of page 47.
We explicitly add the inverses to this generating set.

 The generating set as given in "Tour de gross..."
```
 {x, y, x^3 y^{−1} , x y^3 , x^3 y^{−2} , x^2 y^3 }
```
 This should be the same as
```
 {x, y, x^3 y^5, x y^3 , x^3 y^4 , x^2 y^3 }
```
 The inverses are
```
 {x^5, y^5, x^3 y^1, x^5 y^3 , x^3 y^2 , x^4 y^3 }
```
"""
const generating_set =
let _gens = (# generating set
        (1, 0),  # x
        (0, 1),  # y
        (3, -1), # x^3 y^{−1}
        (1, 3),  # x y^3
        (3, -2), # x^3 y^{−2}
        (2, 3),   # x^2 y^3
    )
    _gens1 = Z6xZ6.(_gens)
    tuple(_gens1..., inv.(_gens1)...) # include the inverses
end

"""
    compute_nr_generators()::Dictionary{Z6xZ6, Int}

Record the number of generators needed to express each element of the group `Z6xZ6`
that can be expressed either as one generator or as a product of two generators. ("generators"
includes inverses here.)

We need logic here only because some products of generators are equal to one of the
generators.
"""
function compute_nr_generators()
    num_gens = Dictionary{Z6xZ6, Int}()
    for g in generating_set
        insert!(num_gens, g, 1)
    end
    for g in generating_set, h in generating_set
        p = g * h
        haskey(num_gens, p) && continue
        insert!(num_gens, p, 2)
    end
    return num_gens
end

"""
    all_elements_present()

Verify, by enumeration, that all elements of Z6xZ6 are generated by no more than two
generators (or inverses).

The particular generating set is defined in "Tour de gross...".
"""
all_elements_present() = all_elements_present(collect(keys(compute_nr_generators())))

function all_elements_present(elements::Vector{Z6xZ6})
    # Get a Vector of all elements in the group
    expected = sort!([Z6xZ6(a, b) for a in 0:5 for b in 0:5])
    return sort(elements) == expected
end

"""
    nr_generators_lookup(g::Z6xZ6)::Int

Return how many generators (from our chosen set) are required to
implement the element `g`.

These rules are designed to agree with what is computed by brute force.
"""
function nr_generators_lookup(g::Z6xZ6)
    (x, y) = xy = (get_x(g), get_y(g))
    xy == (0, 0) && return 2 # In "production" this should be zero
    xy in ((1, 0), (0, 1), (5, 0), (0, 5)) && return 1
    xy in ((3, 3), (0, 3), (3, 0)) && return 2
    (x == 3 || y == 3) && return 1
    return 2
end

"""
    check_nr_generators_lookup()

Verify that the number of generators in the lookup function
agrees with the number of computed generators. Do this for each element
of Z6xZ6. Return `true` upon agreement for all elements.

The number of computed generators is done by brute force. So we assume it
is correct.
"""
function check_nr_generators_lookup()
    # Compute correct numbers by brute force
    numbers_of_generators = compute_nr_generators()
    for (element, num_gens) in pairs(numbers_of_generators)
        # Compare brute force to lookup function.
        num_gens != nr_generators_lookup(element) && return false
    end
    return true
end

end # module Z6Groups
