module Z6xZ6Groups
using Dictionaries: Dictionary, insert!, set!

export generating_set, Z6Group, Z6xZ6Group, compute_nr_generators, all_elements_present,
    nr_generators_lookup, check_nr_generators_lookup

"""
    Z6Group

Represents the cyclic group of order 6.
"""
struct Z6Group
    g::Int
    Z6Group(g::Integer) = new(mod(g, 6))
end

# Choose "multiplication" as the group operation
Base.:*(g::Z6Group, h::Z6Group) = Z6Group(g.g + h.g)
Base.inv(g::Z6Group) = Z6Group(6 - g.g)
Base.isless(g::Z6Group, h::Z6Group) = isless(g.g, h.g) # For lexicographical sort

"""
    Z6xZ6Group

Represents the direct product of two copies of the cyclic group of order 6.
"""
struct Z6xZ6Group
    x::Z6Group
    y::Z6Group
end

get_x(g::Z6xZ6Group)::Int = g.x.g
get_y(g::Z6xZ6Group)::Int = g.y.g

Z6xZ6Group(x::Integer, y::Integer) = Z6xZ6Group(Z6Group(x), Z6Group(y))
Z6xZ6Group((x, y)::Tuple{Integer, Integer}) = Z6xZ6Group(x, y)
Base.:*(g::Z6xZ6Group, h::Z6xZ6Group) = Z6xZ6Group(g.x * h.x, g.y * h.y)
Base.inv(g::Z6xZ6Group) = Z6xZ6Group(inv(g.x), inv(g.y))

function Base.isless(g::Z6xZ6Group, h::Z6xZ6Group) # For lexicographical sort
    isless(g.x, h.x) && return true
    isless(h.x, g.x) && return false
    return isless(g.y, h.y)
end

Base.show(io::IO, g::Z6xZ6Group) = print(io, typeof(g), "(", get_x(g), ", ", get_y(g), ")")

# This is a particular generating set of the group that is defined
# in section 4.2 of "Tour de gross..."
# We explicitly add the inverses to this generating set.
#
#  The generating set as given in "Tour de gross..."
#  {x, y, x^3 y^{−1} , x y^3 , x^3 y^{−2} , x^2 y^3 }
#  This should be the same as
#  {x, y, x^3 y^5, x y^3 , x^3 y^4 , x^2 y^3 }
#  The inverses are
#  {x^5, y^5, x^3 y^1, x^5 y^3 , x^3 y^2 , x^4 y^3 }
#
"""
    generating_set

A particular generating set for Z6xZ6Group that is relatively easy to implement as a circuit.
We include the inverses of each element in this set.
"""
const generating_set =
    let _gens = (# generating set
        (1, 0),  # x
        (0, 1),  # y
        (3, -1), # x^3 y^{−1}
        (1, 3),  # x y^3
        (3, -2), # x^3 y^{−2}
        (2, 3)   # x^2 y^3
        )
        _gens1 = Z6xZ6Group.(_gens)
        tuple(_gens1..., inv.(_gens1)...) # include the inverses
    end

"""
    compute_nr_generators()::Dictionary{Z6xZ6Group, Int}

Record the number of generators needed to express each element of the group `Z6xZ6Group`
that can be expressed as one generator or as a product of two generators. ("generators"
includes inverses here.)

We only need logic here because some products of generators are equal to one of the
generators.
"""
function compute_nr_generators()
    num_gens = Dictionary{Z6xZ6Group, Int}()
    for g in generating_set
        insert!(num_gens, g, 1)
    end
    for g in generating_set, h in generating_set
        p = g * h
        haskey(num_gens, p) && continue
        insert!(num_gens, p, 2)
    end
    return num_gens
end

"""
    all_elements_present()

Verify, by enumeration, that all elements of Z6xZ6 are generated by no more than two
generators (or inverses).

The particular generating set is defined in "Tour de gross...".
"""
all_elements_present() = all_elements_present(collect(keys(compute_nr_generators())))

function all_elements_present(elements::Vector{Z6xZ6Group})
    # Get a Vector of all elements in the group
    expected = sort!([Z6xZ6Group(a, b) for a in 0:5 for b in 0:5])
    sort(elements) == expected
end

"""
    nr_generators_lookup(g::Z6xZ6Group)::Int

Return how many generators (from our chosen set) are required to
implement the element `g`.

These rules are designed to agree with what is computed by brute force.
"""
function nr_generators_lookup(g::Z6xZ6Group)
    (x, y) = xy = (get_x(g), get_y(g))
    xy == (0, 0) && return 2 # In "production" this should be zero
    xy in ((1, 0), (0, 1), (5, 0), (0, 5)) && return 1
    xy in ((3, 3), (0, 3), (3, 0)) && return 2
    (x == 3 || y == 3) && return 1
    return 2
end

"""
    check_nr_generators_lookup()

Check that the number of generators in the lookup function
agrees with the number of computed generators. Do this for each element
of Z6xZ6. Return `true` upon agreement for all elements.

The number of computed generators is done by brute force. So we assume it
is correct.
"""
function check_nr_generators_lookup()
    # Compute correct numbers by brute force
    numbers_of_generators = compute_nr_generators()
    for (element, num_gens) in pairs(numbers_of_generators)
        # Compare brute force to lookup function.
        num_gens != nr_generators_lookup(element) && return false
    end
    return true
end

end # module Z6xZ6Groups
